services:
  fastapi:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    expose:
      - 8000
    networks:
      - website_network
  
  mongodb:
    image: mongo:7.0.5-rc0
    restart: always
    env_file:
      - ./backend/.env.db
    volumes:
      - /etc/volumes/database/db:/data/db
    expose:
    - 27017
    ports:
      - "26017:27017"
    networks:
      - website_network

  nginx:
    image: nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
      - "443:80"
    depends_on:
      - fastapi
      - mongodb
      - web
    networks:
      - website_network
      
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.web
    depends_on:
      - fastapi
    networks:
      - website_network

networks:
  website_network: